@startmindmap

*:UnityScene(SimulationScene)
;

**:SimulationSceneManger
;

***:SimulationWorldHolder
;

****:SimulationWorld
;

**:TrafficSystem
;

**:Roads
;

***:Road_1
;

***:Road_2
;

***:Road_n
;

**:Cars
;

***:Car_1
;

***:Car_2
;

***:Car_n
;
@endmindmap

